services:
  app:
    command: pnpm run dev
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=development
    depends_on:
      mysql:
        condition: service_healthy
    stdin_open: true
    tty: true

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE_DEV}
      MYSQL_USER: ${DB_USERNAME_DEV}
      MYSQL_PASSWORD: ${DB_PASSWORD_DEV}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD_DEV}
      MYSQL_ROOT_HOST: "%"
    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp=1
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${DB_ROOT_PASSWORD_DEV}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_USERNAME_DEV}
      PMA_PASSWORD: ${DB_PASSWORD_DEV}
      PMA_PORT: 3306
    depends_on:
      - mysql

volumes:
  mysql-data:
