services:
  app:
    build: .
    ports:
      - "3001:3001"
    command: pnpm run dev
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    working_dir: /app
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE_DEV}
      MYSQL_USER: ${DB_USERNAME_DEV}
      MYSQL_PASSWORD: ${DB_PASSWORD_DEV}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD_DEV}
      MYSQL_ROOT_HOST: "%"
    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp=1
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_USERNAME_DEV}
      PMA_PASSWORD: ${DB_PASSWORD_DEV}
      PMA_PORT: 3306
    depends_on:
      - mysql

volumes:
  mysql-data:
